name: street_view_platform_interface
description: A Flutter package of street view platform interface.
version: 1.0.9
homepage: https://github.com/zyzdev/flutter_street_view/tree/master/street_view_platform_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  stream_transform: ^2.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
